### ISSUE TITLE
Bench names cannot contain ";"

### ISSUE THREAD

**Issue by devinus** [alco/benchfella#24]
```iex
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Benchfella.Snapshot.parse/1
    lib/benchfella/snapshot.ex:22: anonymous fn(["EncoderBench", "string escaping (JSEX", " unsupported)", "", "1", "1001019"]) in Benchfella.Snapshot.parse/1
    (elixir) lib/enum.ex:977: Enum."-map/2-lc$^0/1-0-"/2
    (elixir) lib/enum.ex:977: Enum."-map/2-lc$^0/1-0-"/2
    lib/benchfella/snapshot.ex:22: Benchfella.Snapshot.parse/1
    lib/benchfella.ex:114: Benchfella.print_formatted_data/3
    (elixir) lib/kernel/cli.ex:70: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by alco** [comment]
Fixed in https://github.com/alco/benchfella/commit/3abf24bc2bed361c032f86fde0ccf70c1378dafa.
